version: "3"
services:
  prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 22733:22733
    environment:
      - TZ=Asia/Seoul
    stdin_open: true # docker run의 -i 옵션. react 한정으로 필요함.
