version: "3"
services:
  prod:
    image: modoojeonse-front-prod
    container_name: "modoojeonse-front-prod"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 22733:22733
    environment:
      - TZ=Asia/Seoul
    stdin_open: true # docker run의 -i 옵션. react 한정으로 필요함.
